/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.iate.reco.ui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import ru.iate.reco.facroty.ProjectFactory;
import ru.iate.reco.obj.RecoProject;

/**
 *
 * @author Luksoral
 */
public class WelcomeWindow extends javax.swing.JFrame {
    
    /**
     * Creates new form WelcomeWindow
     */
    public WelcomeWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        openProject = new javax.swing.JButton();
        newProject = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to ReCo");
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        openProject.setText("Open Project");
        openProject.setAlignmentX(0.5F);
        openProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openProjectActionPerformed(evt);
            }
        });
        getContentPane().add(openProject);

        newProject.setText("New Project");
        newProject.setAlignmentX(0.5F);
        newProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProjectActionPerformed(evt);
            }
        });
        getContentPane().add(newProject);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openProjectActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "ReCo project", "reco");
        fileChooser.setFileFilter(filter);
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                RecoProject project = ProjectFactory.openProject(fileChooser.getSelectedFile().getAbsolutePath());
                ProjectWindow projectWindow = new ProjectWindow(project, fileChooser.getSelectedFile().getAbsolutePath());
                projectWindow.setVisible(true);
                this.dispose();
            } catch (IOException | ClassNotFoundException e) {
                // TODO вывод и анализ ошибки
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_openProjectActionPerformed

    private void newProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProjectActionPerformed
        NewProjectWindow projectWindow = new NewProjectWindow();
        setVisible(false);
        projectWindow.setVisible(true);
        projectWindow.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                WelcomeWindow.this.setVisible(true);
            }
        });
    }//GEN-LAST:event_newProjectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton newProject;
    private javax.swing.JButton openProject;
    // End of variables declaration//GEN-END:variables
}
